#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Telepath\Commands\DeleteWebhook;
use Telepath\Commands\GetWebhookInfo;
use Telepath\Commands\SetWebhook;

$application = new Application();

$application->addCommands([
    new SetWebhook(),
    new DeleteWebhook(),
    new GetWebhookInfo()
]);

$application->run();