#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Telepath\Commands\SetWebhook;

$application = new Application();

$application->addCommands([
    new SetWebhook(),
]);

$application->run();