name: Code Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '12/15 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Generate Code
    runs-on: ubuntu-latest

    env:
      DOCS_URL: https://core.telegram.org/bots/api
      CACHE_DIR: page-cache

    steps:
      - name: Calculate Page Hash
        id: calc-page-hash
        run: |
          hash=$(curl -s "${{ env.DOCS_URL }}" | head -n -1 | sha256sum | awk '{print $1}')
          echo "page_hash=$hash" >> "$GITHUB_OUTPUT"

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          key: page-cache-${{ steps.calc-page-hash.outputs.page_hash }}
          path: ${{ env.CACHE_DIR }}
          restore-keys: |
            page-cache

      - name: Checkout Telepath
        uses: actions/checkout@v4
        with:
          path: telepath

      - name: Checkout Generator
        uses: actions/checkout@v4
        with:
          repository: telepath-php/generator
          path: generator

      - name: Install Dependencies
        run: |
          cd generator
          composer install --no-dev

      - name: Check for changes and generate code
        run: |
          cd generator
          php artisan check --cache-dir="../$CACHE_DIR" ../telepath/src/
          cat "../$CACHE_DIR/environment.txt" >> $GITHUB_ENV

      - name: Commit Changes
        uses: peter-evans/create-pull-request@v6
        if: env.page_changed == 'true' && env.api_version
        with:
          path: telepath
          branch: api-${{ env.api_version }}
          commit-message: "Update code to reflect latest changes to the Bot API documentation"
          delete-branch: true
          title: "Bot API ${{ env.api_version }}"
          body: Updated code to reflect the latest changes to the Bot API documentation regarding API Version ${{ env.api_version }}
          labels: |
            Bot API
            auto-generated
            WTD
          assignees: TiiFuchs
          reviewers: TiiFuchs

      - name: Archive page diff
        uses: actions/upload-artifact@v4
        if: env.page_changed == 'true'
        with:
          name: page-diff
          path: |
            ${{ env.CACHE_DIR }}/*
