name: Tests

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 */3 * *'
  workflow_dispatch:
jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up PHP with Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install NPM Packages
      run: |
        cd ./tests/mtproto
        npm install

    - name: Run Tests
      run: ./vendor/bin/pest
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_APP_ID: ${{ secrets.TELEGRAM_APP_ID }}
        TELEGRAM_APP_HASH: ${{ secrets.TELEGRAM_APP_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
        TELEGRAM_USER: ${{ secrets.TELEGRAM_USER }}
